// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0
// source: response.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createResponse = `-- name: CreateResponse :one
INSERT INTO response (
  request_id,
  driver_phone,
  driver_name,
  driver_latitude,
  driver_longitude
) VALUES (
  $1, $2, $3, $4, $5
)
RETURNING id, request_id, driver_phone, driver_name, driver_latitude, driver_longitude, created_at
`

type CreateResponseParams struct {
	RequestID       int64   `json:"request_id"`
	DriverPhone     string  `json:"driver_phone"`
	DriverName      string  `json:"driver_name"`
	DriverLatitude  float64 `json:"driver_latitude"`
	DriverLongitude float64 `json:"driver_longitude"`
}

func (q *Queries) CreateResponse(ctx context.Context, arg CreateResponseParams) (Response, error) {
	row := q.db.QueryRowContext(ctx, createResponse,
		arg.RequestID,
		arg.DriverPhone,
		arg.DriverName,
		arg.DriverLatitude,
		arg.DriverLongitude,
	)
	var i Response
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.DriverPhone,
		&i.DriverName,
		&i.DriverLatitude,
		&i.DriverLongitude,
		&i.CreatedAt,
	)
	return i, err
}

const deleteResponse = `-- name: DeleteResponse :exec
DELETE FROM response
WHERE driver_phone = $1
`

func (q *Queries) DeleteResponse(ctx context.Context, driverPhone string) error {
	_, err := q.db.ExecContext(ctx, deleteResponse, driverPhone)
	return err
}

const deleteResponseByRequestID = `-- name: DeleteResponseByRequestID :exec
DELETE FROM response
WHERE request_id = $1
`

func (q *Queries) DeleteResponseByRequestID(ctx context.Context, requestID int64) error {
	_, err := q.db.ExecContext(ctx, deleteResponseByRequestID, requestID)
	return err
}

const getResponse = `-- name: GetResponse :one
SELECT id, request_id, driver_phone, driver_name, driver_latitude, driver_longitude, created_at FROM response
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetResponse(ctx context.Context, id int64) (Response, error) {
	row := q.db.QueryRowContext(ctx, getResponse, id)
	var i Response
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.DriverPhone,
		&i.DriverName,
		&i.DriverLatitude,
		&i.DriverLongitude,
		&i.CreatedAt,
	)
	return i, err
}

const getResponseByDriverPhone = `-- name: GetResponseByDriverPhone :one
SELECT id, request_id, driver_phone, driver_name, driver_latitude, driver_longitude, created_at FROM response 
WHERE driver_phone = $1 LIMIT 1
`

func (q *Queries) GetResponseByDriverPhone(ctx context.Context, driverPhone string) (Response, error) {
	row := q.db.QueryRowContext(ctx, getResponseByDriverPhone, driverPhone)
	var i Response
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.DriverPhone,
		&i.DriverName,
		&i.DriverLatitude,
		&i.DriverLongitude,
		&i.CreatedAt,
	)
	return i, err
}

const getResponseByPassengerPhone = `-- name: GetResponseByPassengerPhone :one
SELECT response.id, request_id, driver_phone, driver_name, driver_latitude, driver_longitude, response.created_at, request.id, type, phone, pick_up_latitude, pick_up_longitude, drop_off_latitude, drop_off_longitude, price, status, request.created_at, expire_at FROM response JOIN request ON request.id = response.request_id
WHERE request.phone = $1 LIMIT 1
`

type GetResponseByPassengerPhoneRow struct {
	ID               int64        `json:"id"`
	RequestID        int64        `json:"request_id"`
	DriverPhone      string       `json:"driver_phone"`
	DriverName       string       `json:"driver_name"`
	DriverLatitude   float64      `json:"driver_latitude"`
	DriverLongitude  float64      `json:"driver_longitude"`
	CreatedAt        time.Time    `json:"created_at"`
	ID_2             int64        `json:"id_2"`
	Type             string       `json:"type"`
	Phone            string       `json:"phone"`
	PickUpLatitude   float64      `json:"pick_up_latitude"`
	PickUpLongitude  float64      `json:"pick_up_longitude"`
	DropOffLatitude  float64      `json:"drop_off_latitude"`
	DropOffLongitude float64      `json:"drop_off_longitude"`
	Price            float64      `json:"price"`
	Status           string       `json:"status"`
	CreatedAt_2      time.Time    `json:"created_at_2"`
	ExpireAt         sql.NullTime `json:"expire_at"`
}

func (q *Queries) GetResponseByPassengerPhone(ctx context.Context, phone string) (GetResponseByPassengerPhoneRow, error) {
	row := q.db.QueryRowContext(ctx, getResponseByPassengerPhone, phone)
	var i GetResponseByPassengerPhoneRow
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.DriverPhone,
		&i.DriverName,
		&i.DriverLatitude,
		&i.DriverLongitude,
		&i.CreatedAt,
		&i.ID_2,
		&i.Type,
		&i.Phone,
		&i.PickUpLatitude,
		&i.PickUpLongitude,
		&i.DropOffLatitude,
		&i.DropOffLongitude,
		&i.Price,
		&i.Status,
		&i.CreatedAt_2,
		&i.ExpireAt,
	)
	return i, err
}

const getResponseByRequestID = `-- name: GetResponseByRequestID :one
SELECT id, request_id, driver_phone, driver_name, driver_latitude, driver_longitude, created_at FROM response
WHERE request_id = $1 LIMIT 1
`

func (q *Queries) GetResponseByRequestID(ctx context.Context, requestID int64) (Response, error) {
	row := q.db.QueryRowContext(ctx, getResponseByRequestID, requestID)
	var i Response
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.DriverPhone,
		&i.DriverName,
		&i.DriverLatitude,
		&i.DriverLongitude,
		&i.CreatedAt,
	)
	return i, err
}

const listResponses = `-- name: ListResponses :many
SELECT id, request_id, driver_phone, driver_name, driver_latitude, driver_longitude, created_at FROM response
ORDER BY id
LIMIT $1
OFFSET $2
`

type ListResponsesParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) ListResponses(ctx context.Context, arg ListResponsesParams) ([]Response, error) {
	rows, err := q.db.QueryContext(ctx, listResponses, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Response
	for rows.Next() {
		var i Response
		if err := rows.Scan(
			&i.ID,
			&i.RequestID,
			&i.DriverPhone,
			&i.DriverName,
			&i.DriverLatitude,
			&i.DriverLongitude,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateResponse = `-- name: UpdateResponse :one
UPDATE response
SET driver_phone = $2,
    driver_latitude = $3,
    driver_longitude = $4
WHERE id = $1
RETURNING id, request_id, driver_phone, driver_name, driver_latitude, driver_longitude, created_at
`

type UpdateResponseParams struct {
	ID              int64   `json:"id"`
	DriverPhone     string  `json:"driver_phone"`
	DriverLatitude  float64 `json:"driver_latitude"`
	DriverLongitude float64 `json:"driver_longitude"`
}

func (q *Queries) UpdateResponse(ctx context.Context, arg UpdateResponseParams) (Response, error) {
	row := q.db.QueryRowContext(ctx, updateResponse,
		arg.ID,
		arg.DriverPhone,
		arg.DriverLatitude,
		arg.DriverLongitude,
	)
	var i Response
	err := row.Scan(
		&i.ID,
		&i.RequestID,
		&i.DriverPhone,
		&i.DriverName,
		&i.DriverLatitude,
		&i.DriverLongitude,
		&i.CreatedAt,
	)
	return i, err
}
